version: '3.8'

services:
  otto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otto
    volumes:
      - ./example:/config:ro
      - ./example/workspace:/workspace
      #for gitea mcp #TODO: fix
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
