services:
  otto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otto
    volumes:
      - ./example:/config:ro
      - ./example/workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ./example/.gitconfig:/root/.gitconfig:ro
      - ./example/.git-credentials:/root/.git-credentials:ro
    environment:
      - PYTHONUNBUFFERED=1
    env_file: ./example/.env
    # restart: unless-stopped
